"""Cheap heuristics for stratified sampling and pre-fired structural flags.

These run in a single pass per candidate, ~1ms each. They are intentionally
crude, calibration ground truth comes from hand-labelling, not these.

JD-coupled vocabularies (PRODUCT_COMPANIES, CONSULTING_FIRMS, _ML_TITLE_RE,
etc.) are loaded lazily from the active JD config in src/jd_config.py. To
change them, edit the JD's YAML; do NOT edit this file.
"""
from __future__ import annotations

import re
from functools import lru_cache

from src.jd_config import get_config, register_cache_invalidator
from src.schema import Candidate


# ---------------------------------------------------------------------------
# Lazy, cached accessors. Each is rebuilt when set_config() is called.
# ---------------------------------------------------------------------------

@lru_cache(maxsize=1)
def _ml_title_re() -> re.Pattern:
    return re.compile(get_config().title_patterns.relevant_titles, re.IGNORECASE)


@lru_cache(maxsize=1)
def _retrieval_verb_re() -> re.Pattern:
    """Tokens that count as "retrieval substance" mentions in description text."""
    # Reuse the JD's embedding/vector/eval vocabularies + a small set of
    # general retrieval verbs.
    cfg = get_config()
    tokens = (
        list(cfg.must_haves.embedding_tools)
        + list(cfg.must_haves.vector_db_tools)
        + list(cfg.must_haves.ranking_eval_terms)
        + ["retriev", "rank", "vector", "bm25", "semantic search"]
    )
    # Build alternation, escape special chars
    parts = "|".join(re.escape(t.lower()) for t in tokens)
    return re.compile(rf"\b({parts})\b", re.IGNORECASE)


@lru_cache(maxsize=1)
def _production_verb_re() -> re.Pattern:
    cfg = get_config()
    parts = "|".join(re.escape(v.lower()) for v in cfg.substance.production_verbs)
    return re.compile(rf"\b({parts})\b", re.IGNORECASE)


@lru_cache(maxsize=1)
def _consulting_firms() -> set[str]:
    return {c.lower() for c in get_config().companies.consulting_firms}


@lru_cache(maxsize=1)
def _product_companies() -> set[str]:
    return {c.lower() for c in get_config().companies.product_companies}


@lru_cache(maxsize=1)
def _bigcorp_size() -> str:
    return get_config().sizes.bigcorp_size


@lru_cache(maxsize=1)
def _small_mid_sizes() -> set[str]:
    return set(get_config().sizes.small_mid_sizes)


@lru_cache(maxsize=1)
def _jd_keywords() -> set[str]:
    """Used by `count_jd_keyword_skills` — the JD's named tools."""
    cfg = get_config()
    return {t.lower() for t in (
        cfg.must_haves.embedding_tools
        + cfg.must_haves.vector_db_tools
        + cfg.must_haves.ranking_eval_terms
        + cfg.must_haves.framework_skills
    )}


def _reset_caches() -> None:
    for fn in (
        _ml_title_re, _retrieval_verb_re, _production_verb_re,
        _consulting_firms, _product_companies, _bigcorp_size,
        _small_mid_sizes, _jd_keywords,
    ):
        fn.cache_clear()


register_cache_invalidator(_reset_caches)


# Backward-compat module-level aliases (used by other probe modules).
# These are properties via __getattr__ below.
def __getattr__(name: str):
    if name == "_ML_TITLE_RE":
        return _ml_title_re()
    if name == "_RETRIEVAL_VERB_RE":
        return _retrieval_verb_re()
    if name == "_PRODUCTION_VERB_RE":
        return _production_verb_re()
    if name == "CONSULTING_FIRMS":
        return _consulting_firms()
    if name == "PRODUCT_COMPANIES":
        return _product_companies()
    if name == "BIGCORP_SIZE":
        return _bigcorp_size()
    if name == "SMALL_MID_SIZES":
        return _small_mid_sizes()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


# ---------------------------------------------------------------------------
# Helpers used downstream (no behaviour change vs. previous version)
# ---------------------------------------------------------------------------

def _normalize_company(name: str) -> str:
    return name.strip().lower()


def has_ml_title_anywhere(cand: Candidate) -> bool:
    pat = _ml_title_re()
    if pat.search(cand.profile.current_title or ""):
        return True
    return any(pat.search(r.title or "") for r in cand.career_history)


def has_ml_title_current(cand: Candidate) -> bool:
    return bool(_ml_title_re().search(cand.profile.current_title or ""))


def retrieval_mentions_in_descriptions(cand: Candidate) -> int:
    text = " ".join(r.description or "" for r in cand.career_history)
    return len(_retrieval_verb_re().findall(text))


def production_mentions_in_descriptions(cand: Candidate) -> int:
    text = " ".join(r.description or "" for r in cand.career_history)
    return len(_production_verb_re().findall(text))


def is_consulting_only_career(cand: Candidate) -> bool:
    if not cand.career_history:
        return False
    return all(
        _normalize_company(r.company) in _consulting_firms()
        for r in cand.career_history
    )


def is_bigcorp_only_career(cand: Candidate) -> bool:
    if not cand.career_history:
        return False
    return all(r.company_size == _bigcorp_size() for r in cand.career_history)


def has_product_company_in_history(cand: Candidate) -> bool:
    return any(
        _normalize_company(r.company) in _product_companies()
        for r in cand.career_history
    )


def count_jd_keyword_skills(cand: Candidate) -> int:
    """Count of skills that match JD's named tools (keyword-density proxy)."""
    kws = _jd_keywords()
    return sum(1 for s in cand.skills if s.name.strip().lower() in kws)


# ---------------------------------------------------------------------------
# Honeypot-suspect heuristics (used for bucket E in sampling, NOT the final
# honeypot detector; that lives in src/honeypot.py with stricter rules).
# ---------------------------------------------------------------------------

def salary_paradox(cand: Candidate) -> bool:
    s = cand.redrob_signals.expected_salary_range_inr_lpa
    return s.min > s.max and s.max > 0


def date_inversion_in_career(cand: Candidate) -> bool:
    for r in cand.career_history:
        if r.start_date and r.end_date:
            if r.start_date > r.end_date:
                return True
    return False


def duration_exceeds_experience(cand: Candidate) -> bool:
    total_months = sum(r.duration_months for r in cand.career_history)
    return total_months / 12.0 > cand.profile.years_of_experience + 2


def single_role_exceeds_experience(cand: Candidate) -> bool:
    yoe_months = cand.profile.years_of_experience * 12
    return any(r.duration_months > yoe_months + 12 for r in cand.career_history)


def expert_with_zero_months(cand: Candidate) -> bool:
    n = sum(1 for s in cand.skills if s.proficiency == "expert" and s.duration_months == 0)
    return n >= 3


def fires_any_structural_paradox(cand: Candidate) -> list[str]:
    """Returns a list of paradox names that fire.

    NOTE: salary_paradox is excluded — 18.9% of the synthesized dataset has
    min>max, making it a data artefact rather than a honeypot signal.
    """
    flags = []
    if date_inversion_in_career(cand):
        flags.append("date_inversion")
    if duration_exceeds_experience(cand):
        flags.append("duration>experience")
    if single_role_exceeds_experience(cand):
        flags.append("single_role>experience")
    if expert_with_zero_months(cand):
        flags.append("expert_zero_months")
    return flags


# ---------------------------------------------------------------------------
# Bucket assignment, single pass, mutually exclusive priority order
# ---------------------------------------------------------------------------

def assign_bucket(cand: Candidate) -> str:
    """Assign each candidate to exactly one stratification bucket."""
    paradoxes = fires_any_structural_paradox(cand)

    has_ml_now = has_ml_title_current(cand)
    has_ml_ever = has_ml_title_anywhere(cand)
    retrieval_mentions = retrieval_mentions_in_descriptions(cand)
    has_product_co = has_product_company_in_history(cand)
    jd_kw_count = count_jd_keyword_skills(cand)

    if has_ml_now and has_product_co and retrieval_mentions >= 2:
        return "likely_tier5"

    if paradoxes:
        return "honeypot_suspect"

    if has_ml_ever and (has_product_co or retrieval_mentions >= 3):
        return "likely_tier4"

    if jd_kw_count >= 6 and not has_ml_ever and retrieval_mentions <= 1:
        return "likely_keyword_stuffer"

    if has_ml_ever or retrieval_mentions >= 1 or jd_kw_count >= 2:
        return "adjacent_mid"

    return "random_control"
